### ISSUE TITLE
 Error executing action `install` on resource 'firefox_package[xxxx]'

### ISSUE THREAD

**Issue by rhass-r7** [rapid7-cookbooks/firefox_package#1]
The lazy initializer in poise is not happy with my attempts to call a method defined within the resource. I tried both with and without prefixing the call with 'self', on Chef 11.16.2

@coderanger, if you don't mind taking a look -- I could use some guidance with this specific issue.

```
Converging 1 resources       
Recipe: firefox_poise::default       
  * firefox_package[35.0.5] action install[2014-12-17T01:57:25+00:00] INFO: Processing firefox_package[35.0.5] action install (firefox_poise::default line 20)       


    ================================================================================       
    Error executing action `install` on resource 'firefox_package[35.0.5]'       
    ================================================================================       

    NoMethodError       
    -------------       
    undefined method `upstream_file_checksum' for Chef::Resource::FirefoxPackage       

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:27:in `block in <class:FirefoxPackage>'

       /tmp/kitchen/cookbooks/poise/libraries/lazy_default.rb:38:in `instance_eval'
           /tmp/kitchen/cookbooks/poise/libraries/lazy_default.rb:38:in `set_or_return'

           /tmp/kitchen/cookbooks/poise/libraries/lwrp_polyfill.rb:42:in `block in attribute'
           /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:119:in `block in install_package'

           /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:117:in `install_package'

           /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:39:in `block (2 levels) in action_install'
           /tmp/kitchen/cookbooks/poise/libraries/subcontext_block.rb:79:in `instance_eval'

           /tmp/kitchen/cookbooks/poise/libraries/subcontext_block.rb:79:in `subcontext_block'

           /tmp/kitchen/cookbooks/poise/libraries/notifying_block.rb:33:in `notifying_block'


       /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:38:in `block in action_install'
           /tmp/kitchen/cookbooks/firefox_poise/libraries/firefox_package.rb:37:in `action_install'

           Resource Declaration:
           ---------------------


# In /tmp/kitchen/cookbooks/firefox_poise/recipes/default.rb       

            20: firefox_package '35.0.5'
            21: 


Compiled Resource:       

------------------       
           # Declared in /tmp/kitchen/cookbooks/firefox_poise/recipes/default.rb:20:in `from_file'

           firefox_package("35.0.5") do

  action :install       
             retries 0
             retry_delay 2
             guard_interpreter :default
             cookbook_name :firefox_poise
             recipe_name "default"
             version "35.0.5"

         platform "ubuntu"
      uri "https://download-installer.cdn.mozilla.net/pub/firefox/releases"       
             language "en-US"

           end

       [2014-12-17T01:57:25+00:00] INFO: Running queued delayed notifications before re-raising exception


       Running handlers:
       [2014-12-17T01:57:25+00:00] ERROR: Running exception handlers

       Running handlers complete
       [2014-12-17T01:57:25+00:00] ERROR: Exception handlers complete

[2014-12-17T01:57:25+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out       
Chef Client failed. 0 resources updated in 7.614718235 seconds       
[2014-12-17T01:57:25+00:00] ERROR: firefox_package[35.0.5] (firefox_poise::default line 20) had an error: NoMethodError: undefined method `upstream_file_checksum' for Chef::Resource::FirefoxPackage       
[2014-12-17T01:57:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)       
>>>>>> Converge failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
>>>>>> ----------------------
```

**Comment by coderanger** [comment]
The issue is that `#upstream_file_checksum` is defined on the provider class, not the resource. You can only call methods defined on the resource, not the provider since it hasn't been created yet at that point in the code.

**Comment by rhass-r7** [comment]
"The provider object itself isn't created until right before it is used"

(06:21:53 PM) coderanger: You _can_ create a provider if you need it for something, though chef will create its own later
(06:22:01 PM) coderanger: provider_for_action(self.action)
