### ISSUE TITLE
firefox_package fails to converge

### ISSUE THREAD

**Issue by rhass-r7** [rapid7-cookbooks/firefox_package#6]
Mozilla changed their download server to what appears to be an object store which is resulting in failure to download and parse the index pages. Instead the following xml blob is returned:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>pub/firefox/releases</Key>
<RequestId>089E63F9B3591F07</RequestId>
<HostId>
76bsMyr//SHSqXVVR5spIqpm2p5y2ttcZpED6rQ24Q6svjY7FZBvvAueUU3/nXEi1P2Yogic3uc=
</HostId>
</Error>
```

**Comment by rhass-r7** [comment]
Fixed on master (see https://github.com/rapid7-cookbooks/firefox_package/compare/0ae78bbf270a3a8e02fc573aac8d9f208b748c60...master) for Linux. Windows seems to throw an error in kitchen:

```
$ kitchen converge win
-----> Starting Kitchen (v1.4.2)
-----> Converging <default-windows-2012R2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-windows-2012R2>
       Starting Chef Client, version 12.5.1
       resolving cookbooks for run list: ["firefox_package_test"]
       Synchronizing Cookbooks:
         - firefox_package (0.3.0)
         - chef_handler (1.2.0)
         - firefox_package_test (0.1.0)
         - apt (2.9.2)
         - poise (2.3.2)
         - windows (1.38.2)
         - build-essential (2.2.4)
       Compiling Cookbooks...
       Converging 3 resources
       Recipe: firefox_package_test::default
         * firefox_package[latest-esr] action install

             - install version 1.3.1 of package oga
           - Updating Firefox filename cache: C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd3 with content: Firefox Setup 38.3.0esr.exe
           * chef_gem[oga] action install (up to date)
           * file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd3] action create
             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd3
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd3 from none to 12e8e6
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd3    2015-10-27 19:03:51.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/7f6a902d5266850a1e2eb6384b53e1e8b7dbecd320151027-2912-wumiqx    2015-10-27 19:03:51.000000000 -0700
             @@ -1 +1,2 @@


             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup 38.3.0esr.exe
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup 38.3.0esr.exe from none to 58666a
             (file sizes exceed 10000000 bytes, diff output suppressed)

             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest-esr.ini
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest-esr.ini from none to 83c11c
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest-esr.ini  2015-10-27 19:03:59.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/firefox-latest-esr.ini20151027-2912-cp2v0g  2015-10-27 19:03:59.000000000 -0700
             @@ -1 +1,4 @@
             +[Install]
             + InstallDirectoryPath="C:\Program Files (x86)\Mozilla Firefox\latest-esr_en-US"
             + MaintenanceService=false


           - installing Firefox latest-esr en-US
         * firefox_package[latest] action install
        (up to date)
           - Updating Firefox filename cache: C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e with content: Firefox Setup Stub 41.0.2.exe
        (up to date)
           * file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e] action create
             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e from none to 1d9b58
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e    2015-10-27 19:04:07.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/4d066966ee179ef126842039736f5393bc695e0e20151027-2912-19a1ta2   2015-10-27 19:04:07.000000000 -0700
             @@ -1 +1,2 @@
             +Firefox Setup Stub 41.0.2.exe

             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup Stub 41.0.2.exe
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup Stub 41.0.2.exe from none to 2c4adb
             (new content is binary, diff output suppressed)
           * template[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest.ini] action create
             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest.ini
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest.ini from none to da5b43
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-latest.ini  2015-10-27 19:04:08.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/firefox-latest.ini20151027-2912-11eougc 2015-10-27 19:04:08.000000000 -0700
             @@ -1 +1,4 @@
             +[Install]
             + InstallDirectoryPath="C:\Program Files (x86)\Mozilla Firefox\latest_en-US"
             + MaintenanceService=false


           - installing Firefox latest en-US
         * firefox_package[37.0] action install
        (up to date)
           - Updating Firefox filename cache: C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/9dccc9e5e731a42ead33f91be900fe28c3a6c79d with content: Firefox Setup Stub 37.0.exe
        (up to date)

             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/9dccc9e5e731a42ead33f91be900fe28c3a6c79d
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/9dccc9e5e731a42ead33f91be900fe28c3a6c79d from none to 00f935
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/9dccc9e5e731a42ead33f91be900fe28c3a6c79d    2015-10-27 19:04:09.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/9dccc9e5e731a42ead33f91be900fe28c3a6c79d20151027-2912-fbyx8e    2015-10-27 19:04:09.000000000 -0700
             @@ -1 +1,2 @@
             +Firefox Setup Stub 37.0.exe

             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup Stub 37.0.exe
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/Firefox Setup Stub 37.0.exe from none to f7dece
             (new content is binary, diff output suppressed)
           * template[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-37.0.ini] action create
             - create new file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-37.0.ini
             - update content in file C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-37.0.ini from none to 78ec86
             --- C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\firefox-37.0.ini    2015-10-27 19:04:10.000000000 -0700
             +++ C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/firefox-37.0.ini20151027-2912-kydx7 2015-10-27 19:04:10.000000000 -0700
             @@ -1 +1,4 @@
             +[Install]
             + InstallDirectoryPath="C:\Program Files (x86)\Mozilla Firefox\37.0_en-US"
             + MaintenanceService=false


           - installing Firefox 37.0 en-US
       Starting audit phase

       Firefox Installation
         latest-esr
           is installed
         latest
           is installed (FAILED - 1)
         37.0
           is installed (FAILED - 2)
           is functional when invoked (PENDING: Temporarily skipped with xit)
           is the correct version of Firefox (PENDING: Temporarily skipped with xit)

       Pending: (Failures listed here are expected and do not affect your suite's status)

         1) Firefox Installation 37.0 is functional when invoked
            # Temporarily skipped with xit
            # C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb:84

         2) Firefox Installation 37.0 is the correct version of Firefox
            # Temporarily skipped with xit
            # C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb:89

       Failures:

         1) Firefox Installation latest is installed
            Failure/Error: expect(file(bin_path)).to be_file
       expected `File "C:\Program Files (x86)\Mozilla Firefox\latest_en-US\firefox.exe".file?` to return true, got false
            # C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb:71:in `block (3 levels) in from_file'

         2) Firefox Installation 37.0 is installed
            Failure/Error: expect(file(bin_path)).to be_file
       expected `File "C:\Program Files (x86)\Mozilla Firefox\37.0_en-US\firefox.exe".file?` to return true, got false
            # C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb:80:in `block (3 levels) in from_file'

       Finished in 2.17 seconds (files took 1.69 seconds to load)
       5 examples, 2 failures, 2 pending

       Failed examples:

       rspec 'C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb[1:2:1]' # Firefox Installation latest is installed
       rspec 'C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/firefox_package_test/recipes/default_controls.rb[1:3:1]' # Firefox Installation 37.0 is installed

       Audit phase exception:
         Audit phase found failures - 2/5 controls failed

         Running handlers:
         Running handlers complete
         Chef Client finished, 16/21 resources updated in 03 minutes 41 seconds
           3/5 controls succeeded
       [2015-10-27T19:04:16-07:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2015-10-27T19:04:16-07:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
>>>>>> Converge failed on instance <default-windows-2012R2>.
>>>>>> Please see .kitchen/logs/default-windows-2012R2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
>>>>>> ----------------------
```

**Comment by erran-r7** [comment]
See https://github.com/rapid7-cookbooks/firefox_package/compare/0ae78bbf270a3a8e02fc573aac8d9f208b748c60...master

**Comment by rhass-r7** [comment]
The update xpath code now inadvertently downloads the "stub" installer on Windows, causing the install to silently fail on Windows platforms.
